# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

# RetroAssembly for FreeBSD
# Multi-stage build: compile Node app + native better-sqlite3 addon

ARG BASE_VERSION=15

# --- Stage 1: Builder ---
FROM ghcr.io/daemonless/base:${BASE_VERSION} AS builder

RUN pkg update && pkg install -y \
    node25 npm-node25 git ca_root_nss \
    FreeBSD-toolchain FreeBSD-clang-dev FreeBSD-clibs-dev FreeBSD-runtime-dev

RUN npm install -g pnpm@9

ARG VERSION=latest
RUN if [ "$VERSION" = "latest" ]; then \
      VERSION=$(fetch -qo - https://api.github.com/repos/arianrhodsandlot/retroassembly/releases/latest | jq -r .tag_name); \
    fi && \
    echo "$VERSION" > /version.txt && \
    git clone --depth 1 --branch "$VERSION" https://github.com/arianrhodsandlot/retroassembly.git /src

WORKDIR /src

# Whitelist which packages can run install scripts (workerd has no FreeBSD binary)
ENV SKIP_INSTALL_SIMPLE_GIT_HOOKS=true
RUN node -e "const p=require('./package.json'); p.pnpm={...p.pnpm,onlyBuiltDependencies:['better-sqlite3','esbuild','sharp']}; require('fs').writeFileSync('./package.json',JSON.stringify(p,null,2))"

# Install all deps (dev included for build; better-sqlite3 compiled here with toolchain)
RUN pnpm install --no-frozen-lockfile

# vite-plus bundles rolldown but expects the FreeBSD native binding alongside its dist files
RUN BINDING=$(find /src/node_modules/.pnpm -name "rolldown-binding.freebsd-x64.node" 2>/dev/null | head -1) && \
    if [ -z "$BINDING" ]; then echo "ERROR: rolldown FreeBSD binding not installed" && exit 1; fi && \
    echo "Found binding: $BINDING" && \
    find /src/node_modules/.pnpm -path "*/vite-plus-core*/dist/rolldown/shared" -type d 2>/dev/null | \
      xargs -I{} cp "$BINDING" "{}/rolldown-binding.freebsd-x64.node" && \
    find /src/node_modules/.pnpm -path "*/vite-plus*/binding" -type d 2>/dev/null | \
      xargs -I{} cp "$BINDING" "{}/rolldown-binding.freebsd-x64.node" && \
    echo "Copied rolldown FreeBSD binding to vite-plus dirs"

# Build for node runtime
RUN node --run=build

# Prune to prod deps only (better-sqlite3 already compiled, just removes devDeps)
RUN pnpm prune --prod

# --- Stage 2: Final Runtime ---
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="node25 ca_root_nss"
ARG UPSTREAM_URL="https://api.github.com/repos/arianrhodsandlot/retroassembly/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:8000/"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"
ENV RETROASSEMBLY_RUN_TIME_DATA_DIRECTORY=/data
ENV RETROASSEMBLY_RUN_TIME_STORAGE_DIRECTORY=/data/storage

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="RetroAssembly" \
      org.opencontainers.image.description="Personal retro game collection cabinet in your browser. Play NES, SNES, Genesis, GBA, and more." \
      org.opencontainers.image.source="https://github.com/daemonless/retroassembly" \
      org.opencontainers.image.url="https://retroassembly.com/" \
      org.opencontainers.image.documentation="https://github.com/arianrhodsandlot/retroassembly" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Entertainment" \
      io.daemonless.port="8000" \
      io.daemonless.volumes="/data" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}"

RUN pkg update && pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

WORKDIR /app

COPY --from=builder /src/dist ./dist
COPY --from=builder /src/src/databases ./src/databases
COPY --from=builder /src/node_modules ./node_modules
COPY --from=builder /src/package.json ./
COPY --from=builder /version.txt /app/version

RUN mkdir -p /data && chown -R bsd:bsd /data /app && chmod -R a+rX /app

COPY root/ /

RUN chmod +x /etc/services.d/retroassembly/run /healthz 2>/dev/null || true

# --- Expose (Injected by Generator) ---
EXPOSE 8000

# --- Volumes (Injected by Generator) ---
VOLUME /data